server:
  port: 10102

spring:
  application:
    name: forum-content
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:127.0.0.1:8848}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
  config:
    import:
      - optional:classpath:application-core-defaults.yml

forum:
  domain: content
  features:
    scheduling: true
    mq-consumer: true
    websocket: false
    game-runtime: false

logging:
  file:
    name: ${LOG_FILE:../logs/forum-content/forum-content.log}
