import {
  ArrowRight,
  Close,
  Headset,
  MagicStick,
  Picture,
  Upload,
  VideoCamera,
} from '@element-plus/icons-vue'
import ArticleCreateGallerySection from '@/components/article/ArticleCreateGallerySection.vue'
import ArticleCreateVideoSection from '@/components/article/ArticleCreateVideoSection.vue'
import ArticleAiWriteAssist from '@/components/article/ArticleAiWriteAssist.vue'
import ArticleTagEditor from '@/components/article/ArticleTagEditor.vue'
import MusicHall from '@/components/article/MusicHall.vue'
import BorderGlow from '@/components/common/BorderGlow.vue'
import { useArticleCreate } from '@scripts/views/ArticleCreate'
import { ARTICLE_TYPE } from '@/utils/articleQuestion'

const {
  WangEditor,
  aiWriting,
  tagAiGenerating,
  applyAiContent,
  canAddGallery,
  cascaderOptions,
  clearCover,
  clearSelectedMusic,
  coverAiGenerating,
  coverImageQuality,
  coverInputRef,
  coverPreview,
  coverUploading,
  rejectReason,
  editorMode,
  form,
  galleryInputRef,
  imageModelOptions,
  galleryMaxCount,
  galleryUrls,
  generateAiCover,
  isEdit,
  mdFileInput,
  mdTextareaRef,
  mdWrap,
  mediaMode,
  musicHallOpen,
  onCoverFileSelected,
  onGalleryFilesSelected,
  onMdKeydown,
  onMusicConfirm,
  onVideoFileSelected,
  openCoverPicker,
  openGalleryPicker,
  openMusicHall,
  openVideoPicker,
  removeGalleryAt,
  removeVideo,
  renderedPreview,
  selectedBoard,
  selectedMusic,
  setAiWriting,
  setCoverImageQuality,
  setEditorMode,
  setMediaMode,
  setTagAiGenerating,
  submitting,
  tagIds,
  handleBoardChange,
  handleCancel,
  handleMdFileSelected,
  handleMdInsertImage,
  handlePublish,
  handleSaveDraft,
  videoInputRef,
  videoUrl,
  videoUploadError,
  videoUploadProgress,
  canRetryVideoUpload,
  cancelVideoUpload,
  retryVideoUpload,
  videoUploading,
  galleryUploading,
  galleryPendingCount,
} = useArticleCreate()
