import { useArticleCoverSetup } from '@scripts/views/ArticleCoverSetup'

const {
  COVER_PROMPT_MAX,
  IMAGE_MODEL_OPTIONS,
  Document,
  Download,
  InfoFilled,
  MagicStick,
  Picture,
  Refresh,
  Upload,
  View,
  aiGenerating,
  aiPrompt,
  articleTextPlain,
  canRegenerate,
  coverPreview,
  coverPreviewKey,
  downloadCoverImage,
  fetchCoverHints,
  finishAndSubmitAudit,
  generateAiCover,
  handleCoverChange,
  hintsLoading,
  imageQuality,
  isPublished,
  isVip,
  processing,
  promptLength,
  saveDraftOnly,
  setImageModel,
  title,
} = useArticleCoverSetup()
