<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.pluchon.forum</groupId>
        <artifactId>im</artifactId>
        <version>0.0.1-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <artifactId>im-server</artifactId>
    <name>im-server</name>
    <dependencies>
        <dependency>
            <groupId>org.pluchon.forum</groupId>
            <artifactId>common</artifactId>
        </dependency>
        <dependency>
            <groupId>org.pluchon.forum</groupId>
            <artifactId>im-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.pluchon.forum</groupId>
            <artifactId>auth-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.pluchon.forum</groupId>
            <artifactId>economy-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.pluchon.forum</groupId>
            <artifactId>ai-api</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-loadbalancer</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-openfeign</artifactId>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <mainClass>org.pluchon.forum.ForumImApplication</mainClass>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
