server:
  port: 10104

spring:
  application:
    name: forum-game
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:127.0.0.1:8848}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
  config:
    import:
      - optional:classpath:application-core-defaults.yml

forum:
  domain: game
  features:
    scheduling: true
    mq-consumer: false
    websocket: true
    game-runtime: true

logging:
  file:
    name: ${LOG_FILE:../logs/forum-game/forum-game.log}
