server:
  port: 10102

spring:
  application:
    name: forum-content
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:127.0.0.1:8848}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
  config:
    import:
      - optional:classpath:application-core-defaults.yml
      - optional:classpath:application-core-prod-defaults.yml
  datasource:
    url: ${DB_URL:jdbc:mysql://127.0.0.1:33306/forum_content_db?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true}
    username: ${DB_USERNAME:forum_content}
    password: ${DB_PASSWORD:forum_content_pass}

forum:
  domain: content
  features:
    scheduling: true
    mq-consumer: true
    websocket: false
    game-runtime: false
