package org.pluchon.forum.common.enums;

import lombok.Getter;

// 状态码集合
@Getter
public enum ResultCode {
    SUCCESS(0, "成功"),
    FAILED(1000, "操作没有成功，请稍后再试"),
    FAILED_UNAUTHORIZED(1001, "请先登录后再操作"),
    FAILED_PARAMS_VALIDATE(1002, "填写的内容有误，请检查后重试"),
    FAILED_FORBIDDEN(1003, "你没有权限进行该操作"),
    FAILED_CREATE(1004, "创建失败，请稍后再试"),
    FAILED_NOT_EXISTS(1005, "内容不存在或已被删除"),
    FAILED_USER_EXISTS(1101, "该账号已被注册"),
    FAILED_USER_NOT_EXISTS(1102, "找不到这个用户"),
    FAILED_LOGIN(1103, "账号或密码不正确"),
    FAILED_LOGIN_LOCKED(1210, "登录失败次数过多，请 15 分钟后再试"),
    FAILED_USER_BANNED(1104, "你已被禁言，如有疑问请联系管理员"),
    USER_UNLOGIN(1106,"登录状态已过期，请重新登录"),
    FAILED_ARTICLE(1109,"帖子加载失败，请稍后再试"),
    FAILED_UPDATE_ARTICLE(1110,"帖子修改失败，请确认你是作者且有修改权限"),
    FAILED_DELETE_ARTICLE(1111,"帖子删除失败，请确认你是作者且有删除权限"),
    FAILED_SEND_MESSAGE_BY_MYSELF(1112,"不能给自己发私信哦"),
    FAILED_SMS_RATE_LIMIT(1113,"验证码发送太频繁了，请 30 分钟后再试"),
    FAILED_SMS_CODE_INVALID(1114,"验证码不正确或已过期"),
    FAILED_PHONE_NOT_BOUND(1115,"该手机号还没有绑定账号"),
    FAILED_PHONE_ALREADY_BOUND(1116,"该手机号已绑定其他账号"),
    FAILED_MAIL_RATE_LIMIT(1117,"邮件发送太频繁了，请稍后再试"),
    FAILED_MAIL_CODE_INVALID(1118,"邮箱验证码不正确或已过期"),
    FAILED_MAIL_NOT_BOUND(1119,"该邮箱还没有绑定账号"),
    FAILED_MAIL_ALREADY_BOUND(1120,"该邮箱已绑定其他账号"),
    FAILED_MOFIDY_PASSWORD_ERROR(1123,"密码修改失败，请稍后再试"),
    FAILED_AI_CHECK_IMAGE_ERROR(1124,"图片审核暂时不可用，请稍后再试"),
    FAILED_AI_CHECK_CONTENT_ERROR(1125,"内容审核暂时不可用，请稍后再试"),
    FAILED_CONTENT_VIOLATION(1127, "内容含有不合规信息，请修改后再提交"),
    FAILED_IMAGE_VIOLATION(1128, "图片含有不合规内容，请更换后再上传"),
    FAILED_CHECKIN_DUPLICATE(1129, "今天已经签到啦，明天再来"),
    FAILED_CHECKIN_MAKEUP_CARD_NOT_ENOUGH(1202, "补签卡不够了"),
    FAILED_CHECKIN_MAKEUP_DATE_INVALID(1203, "最近 30 天没有需要补签的日子"),
    FAILED_CHECKIN_MAKEUP_ALREADY_SIGNED(1204, "这一天已经签到过了，不用补签"),
    FAILED_IMAGE_FORMAT_UNSUPPORTED(1130, "只支持 JPG、PNG、GIF 格式的图片"),
    FAILED_IMAGE_COMPRESS(1131, "图片处理失败，请换一张更小的图片"),
    FAILED_EMOJI_DUPLICATE(1132, "这张图片已经在你的收藏里了"),
    FAILED_EMOJI_NOT_EXISTS(1133, "表情收藏不存在，或不属于你"),
    FAILED_EMOJI_LIMIT_EXCEEDED(1134, "表情收藏已达数量上限"),
    FAILED_MESSAGE_IMAGE_INVALID(1135, "图片消息发送失败，请重新上传"),
    FAILED_INVALID_OSS_URL(1136, "图片或视频地址无效，请重新上传"),
    FAILED_SHOP_NOT_EXISTS(1137, "表情包不存在或已下架"),
    FAILED_SHOP_NOT_ONLINE(1138, "这个商品暂时买不了"),
    FAILED_SHOP_ALREADY_PURCHASED(1139, "你已经拥有这个表情包了"),
    FAILED_POINTS_NOT_ENOUGH(1140, "积分不足"),
    FAILED_SHOP_PRICE_INVALID(1141, "商品价格设置有误"),
    FAILED_SHOP_ITEMS_EMPTY(1142, "表情包至少要包含 1 张图片"),
    FAILED_SHOP_ITEMS_LIMIT(1143, "表情包里的图片数量超出上限"),
    FAILED_SHOP_NO_PERMISSION(1144, "你没有修改这个商品的权限"),
    FAILED_ARTICLE_GALLERY_LIMIT(1145, "帖子最多添加 15 张图片"),
    FAILED_ARTICLE_GALLERY_NEEDS_CONTENT(1146, "带图片的帖子正文至少要写 10 个字"),
    FAILED_FOLDER_NOT_EXISTS(1147, "收藏夹不存在或已删除"),
    FAILED_FOLDER_NO_PERMISSION(1148, "不能操作别人的收藏夹"),
    FAILED_FOLDER_NAME_DUPLICATE(1149, "已经有同名收藏夹了"),
    FAILED_FAVORITE_ALREADY_EXISTS(1150, "你已经收藏过这篇帖子"),
    FAILED_FAVORITE_NOT_EXISTS(1151, "找不到这条收藏记录"),
    FAILED_DEFAULT_FOLDER_CANNOT_DELETE(1152, "默认收藏夹不能删除"),
    FAILED_DEFAULT_FOLDER_CANNOT_EDIT(1218, "默认收藏夹不能改名或设置封面"),
    FAILED_FOLDER_COUNT_LIMIT(1219, "收藏夹数量已达上限"),
    FAILED_FOLDER_RENAME_TOO_OFTEN(1220, "改名太频繁了，请稍后再试"),
    FAILED_SHOP_OFFLINE(1221, "该表情包已下架"),
    FAILED_SHOP_DRAFT_COUNT_LIMIT(1222, "草稿数量已达上限"),
    FAILED_SHOP_HAS_PURCHASERS(1223, "已有用户购买，只能下架不能删除"),
    FAILED_FOLDER_VISIBILITY_RATE_LIMIT(1156, "收藏夹公开设置修改太频繁，请稍后再试"),
    FAILED_SEARCH_KEYWORD_EMPTY(1153, "请先输入搜索关键词"),
    FAILED_AI_SEARCH_RATE_LIMIT(1215, "AI 搜索太频繁了，歇一会儿再试"),
    FAILED_AI_SEARCH_DAILY_LIMIT(1216, "今天的 AI 搜索次数用完啦，明天再来"),
    FAILED_PROFILE_CHANGE_DAILY_LIMIT(1217, "今天提交的资料审核次数已达上限，明天再试"),
    FAILED_AUDIT_STATUS_INVALID(1154, "当前帖子状态不能提交审核"),
    FAILED_AUDIT_RETRY_LIMIT(1155, "审核次数已用完，请联系管理员"),
    FAILED_AUDIT_EDIT_LOCKED(1205, "帖子正在审核中，暂时不能编辑，请等待审核结果"),
    FAILED_AUDIT_NOT_AUTHOR(1158, "不能操作别人帖子的审核"),
    FAILED_PUBLISH_NEED_APPROVED(1159, "帖子还没审核通过，暂时不能发布"),
    FAILED_MASCOT_QUOTA(1160, "今天和看板娘聊天的次数用完了，明天再来或开通会员"),
    FAILED_MASCOT_AI(1161, "看板娘正在休息，请稍后再试"),
    FAILED_LOTTERY_INACTIVE(1162, "抽奖活动还没开始或已经结束"),
    FAILED_LOTTERY_TIMES_INVALID(1163, "每次只能抽 1 次或 10 次"),
    FAILED_AI_QUOTA_EXCEEDED(1164, "今天的 AI 使用次数已用完"),
    FAILED_AI_ENGINE(1165, "AI 服务正在休息，请稍后再试"),
    FAILED_CAPTCHA_REQUIRED(1167, "请先完成安全验证"),
    FAILED_CAPTCHA_CHECK(1168, "安全验证没通过，请重新试一次"),
    FAILED_EMOJI_SHOP_NOT_FAVORITABLE(1169, "商城表情不能加入收藏"),
    FAILED_CANNOT_FOLLOW_SELF(1172, "不能关注自己哦"),
    FAILED_REPLY_MEDIA_TOO_MANY(1173, "评论里的附件太多了"),
    FAILED_REPLY_MEDIA_INVALID(1174, "评论附件无效，请重新上传"),
    FAILED_REPLY_CONTENT_EMPTY(1175, "评论内容不能为空"),
    FAILED_DANMAKU_NOT_VIDEO(1176, "只有视频帖可以发弹幕"),
    FAILED_DANMAKU_NOT_PUBLISHED(1177, "帖子还没发布，暂时不能发送或查看弹幕"),
    FAILED_DANMAKU_CONTENT_EMPTY(1178, "弹幕内容不能为空"),
    FAILED_DANMAKU_CONTENT_TOO_LONG(1179, "弹幕内容太长了"),
    FAILED_DANMAKU_COLOR_INVALID(1180, "弹幕颜色不可用"),
    FAILED_DANMAKU_RATE_LIMIT(1181, "弹幕发送太快了，请慢一点"),
    FAILED_DANMAKU_TIME_INVALID(1182, "弹幕出现的时间点无效"),
    FAILED_DANMAKU_WINDOW_TOO_LARGE(1183, "查询的时间范围太大了"),
    FAILED_DANMAKU_MODE_INVALID(1184, "弹幕模式不可用"),
    FAILED_DANMAKU_FONT_SIZE_INVALID(1185, "弹幕字号不可用"),
    FAILED_DANMAKU_DUPLICATE(1186, "请不要重复发送相同的弹幕"),
    FAILED_DANMAKU_MINUTE_LIMIT(1187, "弹幕发送太快了，请慢一点"),
    FAILED_TETRIS_SETTLE_INVALID(1191, "本局成绩校验没通过"),
    FAILED_TETRIS_SETTLE_RATE_LIMIT(1192, "提交太频繁了，请稍后再试"),
    FAILED_ARTICLE_TYPE_INVALID(1193, "帖子类型不可用"),
    FAILED_NOT_QUESTION_ARTICLE(1194, "这不是一个问答帖"),
    FAILED_QUESTION_STATUS_INVALID(1195, "当前问题状态不能进行该操作"),
    FAILED_QUESTION_ANSWER_INVALID(1196, "这个回答不存在或不能被采纳"),
    FAILED_QUESTION_ACCEPT_CONFLICT(1197, "问题已被处理，请刷新后重试"),
    FAILED_SHOP_SERIES_OFFLINE(1199, "这个表情包系列已下架"),
    FAILED_SHOP_EMOJI_DELETED(1200, "这个表情已被删除"),
    FAILED_SHOP_EMOJI_NOT_OWNED(1201, "你还没有这个表情包"),
    FAILED_CURRENT_PASSWORD_INVALID(1211, "当前密码不正确"),
    FAILED_PASSWORD_SAME_AS_OLD(1212, "新密码不能和当前密码一样"),
    FAILED_CODE_IP_RATE_LIMIT(1213, "当前网络发送验证码太频繁，请稍后再试"),
    FAILED_CAPTCHA_IP_RATE_LIMIT(1214, "安全验证请求太频繁，请稍后再试"),
    FAILED_RATE_LIMITED(1206, "操作太频繁了，请稍后再试"),
    FAILED_SERVICE_UNAVAILABLE(1207, "服务正忙，请稍后再试"),
    FAILED_SERVICE_TIMEOUT(1208, "服务响应有点慢，请稍后再试"),
    FAILED_UPLOAD_TOO_LARGE(1209, "文件太大了，请压缩后再上传"),
    ERROR_SERVICES(2000, "服务开小差了，请稍后再试"),
    ;
    // 已废弃码位，禁止复用: 1105 1107 1108 1121 1122 1126 1157 1166 1170 1171 1188 1189 1190 1198 2001
    // 分别对应三次功能下线未清理的残留: VIP 积分订阅、弹幕隐藏、关注幂等化

    final int code;
    final String message;

    ResultCode(int code, String message) {
        this.code = code;
        this.message = message;
    }

    @Override
    public String toString() {
        return "ResultCode:" + code + ",Message:" + message + ".\n";
    }
}
